### ISSUE TITLE
Прошу проверить Д.З.

### ISSUE THREAD

**Issue by AliAlievALive** [AliAlievALive/queueSevrice#1]
Почему-то бейджи показывают build | failing и codecov | unknown

**Comment by coursar** [comment]
Потому что бейджик указывает на master (который у вас fail'иться), а собирается develop

**Comment by coursar** [comment]
Надо смёржить всё в ветку мастер

**Comment by AliAlievALive** [comment]
Смержился, codecov 100% показывает, а вот build так же | failing...

**Comment by AliAlievALive** [comment]
Все, теперь показывает зеленым)
